project/cakeapp/urls.py
from django.urls import path
from .views import IndexView,AboutViewPage,MenuView,ServicView,ContactView,SingleCakeView,SingleChefView,Creat

app_name = 'cakeapp'



urlpatterns = [
    path("creat/",Creat.as_view(), name="creat"),   
    path('',IndexView.as_view(),name='index'),
    path('about/',AboutViewPage.as_view(),name='about'),
    path("menu/", MenuView.as_view(), name="menu"),
    path("chef/", ServicView.as_view(), name="chef"),
    path("contact/", ContactView.as_view(), name="contact"),   
    path("<str:slug>/",SingleCakeView.as_view(), name="single"),   
    path("chef/<str:slug>/",SingleChefView.as_view(), name="single-chef"),   
    
]

project/my_admin/urls.py
from django.urls import path
from .views import  ModerList,ModerDetail,Creat,Update,Delet,Mylogin


app_name = 'my_admin'


urlpatterns = [
    path("", ModerList.as_view(), name="list"),
    path("login", Mylogin.as_view(), name="login"),
    path("detail/<int:pk>/", ModerDetail.as_view(), name="detail"),
    path("creat/", Creat.as_view(), name="create"),
    path("update/<int:pk>/", Update.as_view(), name="update"),
    path("delet/<int:pk>/", Delet.as_view(), name="delet"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cake/',include('cakeapp.urls',namespace='cake')),
    path('moderateur/',include('my_admin.urls',namespace='my_admin')),
    path('auth/',include('user_auth.urls',namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/my_admin/models.py
from django.db import models

# Create your models here.

project/my_admin/forms.py
from django import forms
from cakeapp import models
from cakeapp.models import Cake




class FormCakeAdmin(forms.ModelForm):
    title = forms.CharField()
    price = forms.CharField()
    descri = forms.CharField()
    cake_img = forms.ImageField()
    
    big_descri = forms.CharField()


    class Meta:
        model = Cake
        fields = ['title','price','descri','cake_img','categorivto','big_descri']

project/my_admin/views.py
from django.shortcuts import render
from cakeapp.models import Cake
from .forms import FormCakeAdmin
from django.views.generic import ListView , DetailView ,CreateView , DeleteView , UpdateView
from django.urls import reverse , reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
# Create your views here.

class ModerList(LoginRequiredMixin,ListView):
    model = Cake
    template_name = 'moder/list.html'
    context_object_name = 'context'

class ModerDetail(LoginRequiredMixin,DetailView):
    model = Cake
    template_name = 'moder/detail.html'
    form_class = FormCakeAdmin


class Creat(LoginRequiredMixin,CreateView):
    model = Cake                                                    
    template_name = 'moder/creat.html'
    form_class = FormCakeAdmin
    success_url = reverse_lazy('my_admin:list')

class Update(LoginRequiredMixin,UpdateView):
    model = Cake
    template_name = 'moder/update.html'
    form_class = FormCakeAdmin
    success_url = reverse_lazy('my_admin:list')

class Delet(LoginRequiredMixin,DeleteView):
    model = Cake
    template_name = 'moder/delet.html'
    success_url = reverse_lazy('my_admin:list')

class Mylogin(LoginView):
    redirect_authenticated_user = False
    template_name = 'moder/login.html'

    def get_success_url(self):
        return reverse_lazy('list')

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

project/my_admin/templates/moder/creat.html
<h1>Creat</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

project/my_admin/templates/moder/delet.html
<h1>Delet</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <h4>are you sure for delet this post</h4>
    <input type="submit" value="delet">
</form>

project/my_admin/templates/moder/detail.html
<h1>Detail</h1>
<br> <br >
<h3>datil for product rak fahem</h3>

project/my_admin/templates/moder/list.html
<h1>List</h1>
<br>

<a href="{% url 'my_admin:create' %}">creat</a>

<br>
{% if context %}
  
{% for i in context %}

<a href="{% url 'my_admin:detail' i.id %}">{{i.title}}</a>
<a href="{% url 'my_admin:update' i.id %}">update</a>
<a href="{% url 'my_admin:delet' i.id %}">delet</a>
  
{% endfor %}
{% else %}

<p>Sorry you d'ont have any model</p>

{% endif %}

project/my_admin/templates/moder/login.html
<h1>Loog in</h1>

<form method="post">
    {% csrf_token %}
    
    {% for field in form %}
    {{field.label_tag}}
    {{field}}
    {% endfor %}
    <input type="submit">
</form>

project/my_admin/templates/moder/update.html
<h1>Update</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update">
</form>