project/cakeapp/urls.py
from django.urls import path
from .views import IndexView,AboutViewPage,MenuView,ServicView,ContactView,SingleCakeView,SingleChefView,Creat

app_name = 'cakeapp'



urlpatterns = [
    path("creat/",Creat.as_view(), name="creat"),   
    path('',IndexView.as_view(),name='index'),
    path('about/',AboutViewPage.as_view(),name='about'),
    path("menu/", MenuView.as_view(), name="menu"),
    path("chef/", ServicView.as_view(), name="chef"),
    path("contact/", ContactView.as_view(), name="contact"),   
    path("<str:slug>/",SingleCakeView.as_view(), name="single"),   
    path("chef/<str:slug>/",SingleChefView.as_view(), name="single-chef"),   
    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cake/',include('cakeapp.urls',namespace='cake')),
    path('moderateur/',include('my_admin.urls',namespace='my_admin')),
    path('auth/',include('user_auth.urls',namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/user_auth/urls.py
from django.urls import path
from .views import Profile,Home,LoogIn,Register
from django.contrib.auth.views import LogoutView


app_name = 'user_auth'


urlpatterns = [    
    path('',Home.as_view(),name='home'),
    path('login/',LoogIn.as_view(),name='login'),
    path('register/',Register.as_view(),name='register'),
    path('profile/',Profile.as_view(),name='profile'),   
    path('logout/',LogoutView.as_view(next_page='home'),name="logout"),
]

project/user_auth/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    avatar = models.ImageField(default='avatar.jpg',upload_to='profile_img/')

    def __str__(self):
        return self.user.username

    def save(self,*args, **kwargs):
        super().save(self,*args, **kwargs)

        img = Image.open(self.avatar.path)
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)

project/user_auth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):


    class Meta:
        model = User
        fields = ['username','email','password1','password2',]

project/user_auth/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView,FormView
from django.urls import reverse,reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RegisterForm

from django.contrib.auth import login
# Create your views here.

class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'user/profile.html'
    login_url = 'auth:login'


class Home(TemplateView):
    template_name = 'user/home.html'



class LoogIn(LoginView):
    redirect_authenticated_user = False
    template_name = 'user/login.html'

    def get_success_url(self):
        messages.info(self.request,'welcom to your profile')
        return reverse_lazy('auth:profile')

    def form_invalid(self, form):
        messages.error(self.request,'ghalat awld lklba')
        return self.render_to_response(self.get_context_data(form=form))



class Register(FormView):
    redirect_authenticated_user = True
    template_name = 'user/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('auth:profile')
    

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated:
           return redirect('auth:profile')
        

    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request,user)
        return redirect(self.success_url)

project/user_auth/templates/user/home.html
<h1>Home</h1>

project/user_auth/templates/user/login.html
<h1>Loog In</h1>

<form method="post">
    {% csrf_token %}
    {% for field in form %}
      {{field.label_tag}}
      {{field}}
      {% if field.errors %}
        {{field.errors}}
      {% endif %}
    {% endfor %}
    <input type="submit" value="login">
    <br><br>
    <a href="{% url 'auth:register' %}">Register</a>
</form>

project/user_auth/templates/user/profile.html
<h1>Profile</h1>

<br>
<h2>{{request.user.first_name}} {{request.user.last_name}}</h2>
<h3>{{request.user.email}}</h3>
<h3>{{request.user.username}}</h3>
<img src="{{request.user.profile.avatar.url}}"/>
<br>
<br>
<a href="{% url 'auth:login' %}">Logout</a>

project/user_auth/templates/user/register.html
<h1>Register</h1>

<form method="post">
    {% csrf_token %}
    {% for field in form %}
      {{field.label_tag}}
      {{field}}
      {% if field.errors %}
        {{field.errors}}
      {% endif %}
    {% endfor %}
    <input type="submit" value="Register">
    <br><br>
    <a href="{% url 'auth:login' %}">Login</a>
</form>