project/cakeapp/urls.py
from django.urls import path
from .views import IndexView,AboutViewPage,MenuView,ServicView,ContactView,SingleCakeView,SingleChefView,Creat

app_name = 'cakeapp'



urlpatterns = [
    path("creat/",Creat.as_view(), name="creat"),   
    path('',IndexView.as_view(),name='index'),
    path('about/',AboutViewPage.as_view(),name='about'),
    path("menu/", MenuView.as_view(), name="menu"),
    path("chef/", ServicView.as_view(), name="chef"),
    path("contact/", ContactView.as_view(), name="contact"),   
    path("<str:slug>/",SingleCakeView.as_view(), name="single"),   
    path("chef/<str:slug>/",SingleChefView.as_view(), name="single-chef"),   
    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cake/',include('cakeapp.urls',namespace='cake')),
    path('moderateur/',include('my_admin.urls',namespace='my_admin')),
    path('auth/',include('user_auth.urls',namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/cakeapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from requests import request
import os
from twilio.rest import Client

cate = (
    ('BIRTHDAY','BIRTHDAY'),
    ('WEDDING','WEDDING'),
    ('CUSTOM','CUSTOM'),  

)



class Cake(models.Model):
    title = models.CharField(max_length=50,blank=False,null=True)
    price = models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    descri = models.TextField(max_length=1000,null=True,blank=True)
    cake_img = models.ImageField(upload_to='imgs_cake/',null=True,blank=True)
    #categori = models.ForeignKey('Qatego',on_delete=models.CASCADE,null=True,blank=True)
    categorivto = models.CharField(max_length=50,choices=cate,null=True,blank=True)
    big_descri = RichTextField(null=True,blank=True)
    slug = models.SlugField(null=True,blank=True)


    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(Cake,self).save(*args, **kwargs)

    def __str__(self):
        return self.title


#class Qatego(models.Model):
    #name = models.CharField(max_length=50,null=True,blank=True)


    #def  __str__(self):
        #return self.name


class Chef(models.Model):
    name = models.CharField(max_length=50,null=False,blank=True)
    spes = models.TextField(max_length=300,null=True,blank=True)
    chef_img = models.ImageField(upload_to='imgs_chef/',null=True,blank=True)
    slug = models.SlugField(null=True,blank=True)
    


    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Chef,self).save(*args, **kwargs)
    

    def __str__(self):
        return self.name


class ComandForminTemplate(models.Model):
    first_name = models.CharField(max_length=50,null=True,blank=True)
    last_name = models.CharField(max_length=50,null=True,blank=True)
    email = models.CharField(max_length=100,null=True,blank=True)
    phone = models.CharField(max_length=15,null=True,blank=True)
    #cake = models.OneToOneField(Cake,on_delete=models.CASCADE)

    
    def __str__(self):
        return self.phone



class ContactCheFform(models.Model):
    first = models.CharField(max_length=50)
    last = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.IntegerField()
    mess = models.TextField(max_length=500,null=True,blank=True)

    class Meta:
        verbose_name = 'Contact Chef'
        verbose_name_plural = 'Contact Form'


    def __str__(self):
        return self.email


class ContactSms(models.Model):
    name = models.CharField(max_length=50)
    emaltext = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=100)

    def __str__(self):
        return self.name

project/cakeapp/forms.py
from django import forms
from . import models
from .models import ComandForminTemplate,ContactSms,Cake

class CommandForm(forms.Form):
  class Meta:
      model = ComandForminTemplate
      fields = '__all__'


class ContactForm(forms.ModelForm):
    name = forms.CharField(widget = forms.TextInput (attrs={"class":"form-control","placeholder":"name"}))
    emaltext = forms.CharField(widget = forms.TextInput (attrs={"class":"form-control","placeholder":"email"}))
    subject = forms.CharField(widget = forms.TextInput (attrs={"class":"form-control","placeholder":"subject"}))
    message = forms.CharField(widget = forms.Textarea (attrs={"class":"form-control","placeholder":"message"}))

    class Meta:
      model = ContactSms
      fields = ['name','emaltext','subject','message']



class CreatForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput)
    price = forms.DecimalField(widget=forms.NumberInput)
    descri = forms.CharField(widget=forms.TextInput)
    cake_img = forms.ImageField()
    #categori = forms.ForeignKey('Qatego',on_delete=forms.CASCADE,null=True,blank=True)
    categorivto = forms.ChoiceField(choices=models.cate)
    big_descri = forms.CharField(widget=forms.Textarea)
    #slug = forms.SlugField()
    

    class Meta:
      model = Cake
      fields = ['title','price','descri','cake_img','categorivto','big_descri']

project/cakeapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView , DetailView ,CreateView
from .models import Cake,Chef,ContactSms
from .forms import CommandForm,ContactForm,CreatForm
from .models import ComandForminTemplate
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views.generic import View
from project import settings
from twilio.rest import Client
from django.conf import settings
from django.urls import reverse,reverse_lazy

# Create your views here.


class IndexView(TemplateView):
    template_name = 'pages/index.html'

class AboutViewPage(TemplateView):
    template_name = 'pages/about.html'
    
class MenuView(ListView):
    template_name = 'pages/menu.html'
    model = Cake
    context_object_name = 'contex'

class ContactView(TemplateView):
    model = ContactSms
    form_class = ContactForm
    template_name = 'pages/contact.html'

    def post(self, request, **kwargs):
        name = request.POST.get('name')
        emaltext = request.POST.get('emaltext')
        subject = request.POST.get('subject')                  #this is  methode form in html page
        message = request.POST.get('message')


        ContactSms.objects.create(
            name=name,
            emaltext=emaltext,
            subject=subject,
            message=message,
        )
        return redirect('cake:contact')
    
    

  



class SingleCakeView(DetailView):
    model = Cake
    context_object_name = 'hoho'
    template_name = 'pages/single-cake.html'

    def post(self, request, **kwargs):
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        email = request.POST.get('email')                  #this is  methode form in html page
        phone = request.POST.get('phone')                        #in admin 

        # save the form data to the database
        ComandForminTemplate.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            phone=phone,
        )

        return redirect('cake:contact')


class ServicView(ListView):
    model = Chef
    template_name = 'pages/servise.html'
    context_object_name = 'contex'



class SingleChefView(DetailView):
    model = Chef
    context_object_name = 'chef'
    template_name = 'pages/single-chef.html'


    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommandForm()
        return context

    def post(self, request,*args, **kwargs):
        if request.method == 'POST':
            email = request.POST['email']
            phone = request.POST['phone']
            message = request.POST['messag']           #FORM SEND EMAIL

        send_mail(
            email,
            message,
            phone,
            
            [settings.EMAIL_HOST_USER],
            fail_silently=False,
        )        

        return redirect('cake:contact')

        
       
class Creat(CreateView):
    model = Cake
    #fields = ['title','price','descri','cake_img','categorivto','big_descri']
    form_class = CreatForm
    template_name = 'crud/creat.html'
    success_url = reverse_lazy('cake:index')
    

project/cakeapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>CakeZone - Cake Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Oswald:wght@500;600;700&family=Pacifico&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/single.css' %}" rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid px-0 d-none d-lg-block" >
        <div class="row gx-0" >
            <div class="col-lg-4 text-center bg-light-subtle py-3">
                <div class="d-inline-flex align-items-center justify-content-center">
                    <i class="bi bi-envelope fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Email Us</h6>
                        <span>info@example.com</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-center bg-primary border-inner py-3">
                <div class="d-inline-flex align-items-center justify-content-center">
                    <a href="index.html" class="navbar-brand">
                        <h1 class="m-0 text-uppercase text-white"><i class="fa fa-birthday-cake fs-1 text-dark me-3"></i>CakeZone</h1>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 text-center bg-light py-3">
                <div class="d-inline-flex align-items-center justify-content-center">
                    <i class="bi bi-phone-vibrate fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Call Us</h6>
                        <span>+012 345 6789</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="index.html" class="navbar-brand d-block d-lg-none">
            <h1 class="m-0 text-uppercase text-white"><i class="fa fa-birthday-cake fs-1 text-primary me-3"></i>CakeZone</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto mx-lg-auto py-0">
                <a href="{% url 'cake:index' %}" class="nav-item nav-link active">Home</a>
                <a href="{% url 'cake:about' %}" class="nav-item nav-link">About Us</a>
                <a href="{% url 'cake:menu' %}" class="nav-item nav-link">Menu & Pricing</a>
                <a href="{% url 'cake:chef' %}" class="nav-item nav-link">Master Chefs</a>

                <a href="{% url 'cake:contact' %}" class="nav-item nav-link">Contact Us</a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->

{% block cake %}
<h1>hello</h1>
{% endblock cake %}
    


     <!-- Footer Start -->
     <div class="container-fluid bg-primary text-secondary" style="margin-top: 90px;background-color: aqua;">
        <div class="container">
            <div class="row gx-5 ">
                <div class="col-lg-4 col-md-6 mb-lg-n5 " style="height: 350px;">
                    <div class="d-flex flex-column align-items-center justify-content-center text-center h-100 bg-light border-inner p-4">
                        <a href="index.html" class="navbar-brand">
                            <h1 class="m-0 text-uppercase text-white"><i class="fa fa-birthday-cake fs-1 text-dark me-3"></i>CakeZone</h1>
                        </a>
                        <p class="mt-3">Lorem diam sit erat dolor elitr et, diam lorem justo labore amet clita labore stet eos magna sit. Elitr dolor eirmod duo tempor lorem, elitr clita ipsum sea. Nonumy rebum et takimata ea takimata amet gubergren, erat rebum magna lorem stet eos. Diam amet et kasd eos duo dolore no.</p>
                    </div>
                </div>
                <div class="col-lg-8 col-md-6">
                    <div class="row gx-5 text-white" style="font-size:20px;font-weight: bold;font-family: Arial, Helvetica, sans-serif;">
                        <div class="col-lg-4 col-md-12 pt-5 mb-5 ">
                            <h4 class="text-primary text-uppercase mb-4">Get In Touch</h4>
                            <div class="d-flex mb-2">
                                <i class="bi bi-geo-alt text-primary me-2"></i>
                                <p class="mb-0">Street, New York,123 USA</p>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-envelope-open text-primary me-2"></i>
                                <p class="mb-0">info@example.com</p>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-telephone text-primary me-2"></i>
                                <p class="mb-0">+012 345 67890</p>
                            </div>
                            <div class="d-flex mt-4">
                                <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                                <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                                <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5 text-dark">
                            <h4 class="text-primary text-uppercase  mb-4 ">Quick Links</h4>
                            <div class="d-flex flex-column  justify-content-start text-dark ">
                                <a class="text-black mb-2"  href="#"><i class="bi bi-arrow-right text-dark me-2"></i>Home</a>
                                <a class="text-black mb-2"  href="#"><i class="bi bi-arrow-right text-dark me-2"></i>About Us</a>
                                <a class="text-black mb-2"  href="#"><i class="bi bi-arrow-right text-dark me-2"></i>Our Services</a>
                                <a class="text-black mb-2"  href="#"><i class="bi bi-arrow-right text-dark me-2"></i>Meet The Team</a>
                                <a class="text-black mb-2"  href="#"><i class="bi bi-arrow-right text-dark me-2"></i>Latest Blog</a>
                                <a class="text-black"  href="#"><i class="bi bi-arrow-right text-dark me-2"></i>Contact Us</a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5 bg-black">
                          
                            <h4 class="text-primary text-uppercase mb-4 bg-light" style="border: 5px;border-radius: 3px;">Newsletter</h4>
                            <p>Amet justo diam dolor rebum lorem sit stet sea justo kasd</p>
                            <form action=""  style="width: 185px;" >
                                <div class="input-group" >
                                    <input type="text" style="height: 40px;" class="form-control border-white p-3" placeholder="Your Email">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="container-fluid text-secondary py-4" style="background: #111111;">
        <div class="container text-center">
            <p class="mb-0">&copy; <a class="text-white border-bottom" href="#">Your Site Name</a>. All Rights Reserved. Designed by <a class="text-white border-bottom" href="https://htmlcodex.com">HTML Codex</a></p>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-inner py-3 fs-4 back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>