project/cakeapp/urls.py
from django.urls import path
from .views import IndexView,AboutViewPage,MenuView,ServicView,ContactView,SingleCakeView,SingleChefView,Creat

app_name = 'cakeapp'



urlpatterns = [
    path("creat/",Creat.as_view(), name="creat"),   
    path('',IndexView.as_view(),name='index'),
    path('about/',AboutViewPage.as_view(),name='about'),
    path("menu/", MenuView.as_view(), name="menu"),
    path("chef/", ServicView.as_view(), name="chef"),
    path("contact/", ContactView.as_view(), name="contact"),   
    path("<str:slug>/",SingleCakeView.as_view(), name="single"),   
    path("chef/<str:slug>/",SingleChefView.as_view(), name="single-chef"),   
    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cake/',include('cakeapp.urls',namespace='cake')),
    path('moderateur/',include('my_admin.urls',namespace='my_admin')),
    path('auth/',include('user_auth.urls',namespace='auth')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/cakeapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from requests import request
import os
from twilio.rest import Client

cate = (
    ('BIRTHDAY','BIRTHDAY'),
    ('WEDDING','WEDDING'),
    ('CUSTOM','CUSTOM'),  

)



class Cake(models.Model):
    title = models.CharField(max_length=50,blank=False,null=True)
    price = models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    descri = models.TextField(max_length=1000,null=True,blank=True)
    cake_img = models.ImageField(upload_to='imgs_cake/',null=True,blank=True)
    #categori = models.ForeignKey('Qatego',on_delete=models.CASCADE,null=True,blank=True)
    categorivto = models.CharField(max_length=50,choices=cate,null=True,blank=True)
    big_descri = RichTextField(null=True,blank=True)
    slug = models.SlugField(null=True,blank=True)


    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(Cake,self).save(*args, **kwargs)

    def __str__(self):
        return self.title


#class Qatego(models.Model):
    #name = models.CharField(max_length=50,null=True,blank=True)


    #def  __str__(self):
        #return self.name


class Chef(models.Model):
    name = models.CharField(max_length=50,null=False,blank=True)
    spes = models.TextField(max_length=300,null=True,blank=True)
    chef_img = models.ImageField(upload_to='imgs_chef/',null=True,blank=True)
    slug = models.SlugField(null=True,blank=True)
    


    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Chef,self).save(*args, **kwargs)
    

    def __str__(self):
        return self.name


class ComandForminTemplate(models.Model):
    first_name = models.CharField(max_length=50,null=True,blank=True)
    last_name = models.CharField(max_length=50,null=True,blank=True)
    email = models.CharField(max_length=100,null=True,blank=True)
    phone = models.CharField(max_length=15,null=True,blank=True)
    #cake = models.OneToOneField(Cake,on_delete=models.CASCADE)

    
    def __str__(self):
        return self.phone



class ContactCheFform(models.Model):
    first = models.CharField(max_length=50)
    last = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.IntegerField()
    mess = models.TextField(max_length=500,null=True,blank=True)

    class Meta:
        verbose_name = 'Contact Chef'
        verbose_name_plural = 'Contact Form'


    def __str__(self):
        return self.email


class ContactSms(models.Model):
    name = models.CharField(max_length=50)
    emaltext = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=100)

    def __str__(self):
        return self.name

project/cakeapp/forms.py
from django import forms
from . import models
from .models import ComandForminTemplate,ContactSms,Cake

class CommandForm(forms.Form):
  class Meta:
      model = ComandForminTemplate
      fields = '__all__'


class ContactForm(forms.ModelForm):
    name = forms.CharField(widget = forms.TextInput (attrs={"class":"form-control","placeholder":"name"}))
    emaltext = forms.CharField(widget = forms.TextInput (attrs={"class":"form-control","placeholder":"email"}))
    subject = forms.CharField(widget = forms.TextInput (attrs={"class":"form-control","placeholder":"subject"}))
    message = forms.CharField(widget = forms.Textarea (attrs={"class":"form-control","placeholder":"message"}))

    class Meta:
      model = ContactSms
      fields = ['name','emaltext','subject','message']



class CreatForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput)
    price = forms.DecimalField(widget=forms.NumberInput)
    descri = forms.CharField(widget=forms.TextInput)
    cake_img = forms.ImageField()
    #categori = forms.ForeignKey('Qatego',on_delete=forms.CASCADE,null=True,blank=True)
    categorivto = forms.ChoiceField(choices=models.cate)
    big_descri = forms.CharField(widget=forms.Textarea)
    #slug = forms.SlugField()
    

    class Meta:
      model = Cake
      fields = ['title','price','descri','cake_img','categorivto','big_descri']

project/cakeapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView , DetailView ,CreateView
from .models import Cake,Chef,ContactSms
from .forms import CommandForm,ContactForm,CreatForm
from .models import ComandForminTemplate
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views.generic import View
from project import settings
from twilio.rest import Client
from django.conf import settings
from django.urls import reverse,reverse_lazy

# Create your views here.


class IndexView(TemplateView):
    template_name = 'pages/index.html'

class AboutViewPage(TemplateView):
    template_name = 'pages/about.html'
    
class MenuView(ListView):
    template_name = 'pages/menu.html'
    model = Cake
    context_object_name = 'contex'

class ContactView(TemplateView):
    model = ContactSms
    form_class = ContactForm
    template_name = 'pages/contact.html'

    def post(self, request, **kwargs):
        name = request.POST.get('name')
        emaltext = request.POST.get('emaltext')
        subject = request.POST.get('subject')                  #this is  methode form in html page
        message = request.POST.get('message')


        ContactSms.objects.create(
            name=name,
            emaltext=emaltext,
            subject=subject,
            message=message,
        )
        return redirect('cake:contact')
    
    

  



class SingleCakeView(DetailView):
    model = Cake
    context_object_name = 'hoho'
    template_name = 'pages/single-cake.html'

    def post(self, request, **kwargs):
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        email = request.POST.get('email')                  #this is  methode form in html page
        phone = request.POST.get('phone')                        #in admin 

        # save the form data to the database
        ComandForminTemplate.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            phone=phone,
        )

        return redirect('cake:contact')


class ServicView(ListView):
    model = Chef
    template_name = 'pages/servise.html'
    context_object_name = 'contex'



class SingleChefView(DetailView):
    model = Chef
    context_object_name = 'chef'
    template_name = 'pages/single-chef.html'


    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommandForm()
        return context

    def post(self, request,*args, **kwargs):
        if request.method == 'POST':
            email = request.POST['email']
            phone = request.POST['phone']
            message = request.POST['messag']           #FORM SEND EMAIL

        send_mail(
            email,
            message,
            phone,
            
            [settings.EMAIL_HOST_USER],
            fail_silently=False,
        )        

        return redirect('cake:contact')

        
       
class Creat(CreateView):
    model = Cake
    #fields = ['title','price','descri','cake_img','categorivto','big_descri']
    form_class = CreatForm
    template_name = 'crud/creat.html'
    success_url = reverse_lazy('cake:index')
    

project/cakeapp/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block cake %}


    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">About Us</h1>
                <a href="">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="">About</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- About Start -->
    <div class="container-fluid pt-5">
        <div class="container">
            <div class="section-title position-relative text-center mx-auto mb-5 pb-3" style="max-width: 600px;">
                <h2 class="text-primary font-secondary">About Us</h2>
                <h1 class="display-4 text-uppercase">Welcome To CakeZone</h1>
            </div>
            <div class="row gx-5">
                <div class="col-lg-5 mb-5 mb-lg-0" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="{% static 'img/about.jpg' %}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 pb-5">
                    <h4 class="mb-4">Tempor erat elitr rebum clita. Diam dolor diam ipsum erat lorem sed stet labore lorem sit clita duo</h4>
                    <p class="mb-5">Tempor erat elitr at rebum at at clita. Diam dolor diam ipsum et tempor sit. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet magna</p>
                    <div class="row g-5">
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center justify-content-center bg-primary border-inner mb-4" style="width: 90px; height: 90px;">
                                <i class="fa fa-heartbeat fa-2x text-white"></i>
                            </div>
                            <h4 class="text-uppercase">100% Healthy</h4>
                            <p class="mb-0">Labore justo vero ipsum sit clita erat lorem magna clita nonumy dolor magna dolor vero</p>
                        </div>
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center justify-content-center bg-primary border-inner mb-4" style="width: 90px; height: 90px;">
                                <i class="fa fa-award fa-2x text-white"></i>
                            </div>
                            <h4 class="text-uppercase">Award Winning</h4>
                            <p class="mb-0">Labore justo vero ipsum sit clita erat lorem magna clita nonumy dolor magna dolor vero</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Facts Start -->
    <div class="container-fluid bg-img py-5 mb-5">
        <div class="container py-5" >
            <div class="row gx-5 gy-4" >
                <div class="col-lg-3 col-md-6" >
                    <div class="d-flex">
                        <div class="bg-primary border-inner d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                            <i class="fa fa-star text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h6 class="text-primary text-uppercase">Our Experience</h6>
                            <h1 class="display-5 text-white mb-0" data-toggle="counter-up">12345</h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex">
                        <div class="bg-primary border-inner d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                            <i class="fa fa-users text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h6 class="text-primary text-uppercase">Cake Specialist</h6>
                            <h1 class="display-5 text-white mb-0" data-toggle="counter-up">12345</h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex">
                        <div class="bg-primary border-inner d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                            <i class="fa fa-check text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h6 class="text-primary text-uppercase">Complete Project</h6>
                            <h1 class="display-5 text-white mb-0" data-toggle="counter-up">12345</h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex">
                        <div class="bg-primary border-inner d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                            <i class="fa fa-mug-hot text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h6 class="text-primary text-uppercase">Happy Clients</h6>
                            <p class="display-5 text-light mb-0" data-toggle="counter-up">12345</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Facts End -->





{% endblock cake %}

project/cakeapp/templates/pages/contact.html
{% extends 'base.html' %}

{% block cake %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">Contact Us</h1>
                <a href="{% url 'cake:index' %}">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="{% url 'cake:contact' %}">Contact</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid contact position-relative px-5" style="margin-top: 90px;">
        <div class="container">
            <div class="row g-5 mb-5">
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-geo-alt fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Our Office</h6>
                        <span>123 Street, New York, USA</span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-envelope-open fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Email Us</h6>
                        <span>info@example.com</span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-phone-vibrate fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Call Us</h6>
                        <span>+012 345 6789</span>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <input type="text" class="form-control bg-light border-0 px-4" placeholder="Your Name" name="name" style="height: 55px;">
                            </div>
                            <div class="col-sm-6">
                                <input type="email" class="form-control bg-light border-0 px-4" placeholder="Your Email"  name="emaltext" style="height: 55px;">
                            </div>
                            <div class="col-sm-12">
                                <input type="text" class="form-control bg-light border-0 px-4" placeholder="Subject" name="subject" style="height: 55px;">
                            </div>
                            <div class="col-sm-12">
                                <textarea class="form-control bg-light border-0 px-4 py-3" rows="4" placeholder="Message" name="message"></textarea>
                            </div>
                            <div class="col-sm-12">
                                <button class="btn btn-primary border- w-100 py-3" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                      
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock cake %}

project/cakeapp/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}
{% block cake %}
  <!-- Background image -->
  <div class="p-5 text-center bg-image" style="
      background-image: url('https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80');
      height: 400px;
    ">
    <div class="mask" style="">
      <div class="d-flex justify-content-center align-items-center h-100" style="border:0px;">
        <div class="text-white">
          <h1 class="mb-3">Heading</h1>
          <a class="btn btn-outline-light btn-lg" href="#!" role="button">Call to action</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->


    <!-- Video Modal Start -->
    <div class="modal fade" id="videoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Youtube Video</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- 16:9 aspect ratio -->
                    <div class="ratio ratio-16x9">
                        <iframe class="embed-responsive-item" src="" id="video" allowfullscreen allowscriptaccess="always"
                            allow="autoplay"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Video Modal End -->


    <!-- About Start -->
    <div class="container-fluid pt-5">
        <div class="container">
            <div class="section-title position-relative text-center mx-auto mb-5 pb-3" style="max-width: 600px;">
                <h2 class="text-primary font-secondary">About Us</h2>
                <h1 class="display-4 text-uppercase">Welcome To CakeZone</h1>
            </div>
            <div class="row gx-5">
                <div class="col-lg-5 mb-5 mb-lg-0" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="{% static 'img/about.jpg' %}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 pb-5">
                    <h4 class="mb-4">Tempor erat elitr rebum clita. Diam dolor diam ipsum erat lorem sed stet labore lorem sit clita duo</h4>
                    <p class="mb-5">Tempor erat elitr at rebum at at clita. Diam dolor diam ipsum et tempor sit. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet magna</p>
                    <div class="row g-5">
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center justify-content-center bg-primary border-inner mb-4" style="width: 90px; height: 90px;">
                                <i class="fa fa-heartbeat fa-2x text-white"></i>
                            </div>
                            <h4 class="text-uppercase">100% Healthy</h4>
                            <p class="mb-0">Labore justo vero ipsum sit clita erat lorem magna clita nonumy dolor magna dolor vero</p>
                        </div>
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center justify-content-center bg-primary border-inner mb-4" style="width: 90px; height: 90px;">
                                <i class="fa fa-award fa-2x text-white"></i>
                            </div>
                            <h4 class="text-uppercase">Award Winning</h4>
                            <p class="mb-0">Labore justo vero ipsum sit clita erat lorem magna clita nonumy dolor magna dolor vero</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->





    <!-- Service Start -->
    <div class="container-fluid service position-relative px-5 mt-5" style="margin-bottom: 135px;">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <h4 class="text-uppercase mb-3">Birthday Cake</h4>
                        <p>Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo amet tempor amet kasd lorem dolor ipsum</p>
                        <a class="text-uppercase text-dark" href="">Read More <i class="bi bi-arrow-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <h4 class="text-uppercase mb-3">Wedding Cake</h4>
                        <p>Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo amet tempor amet kasd lorem dolor ipsum</p>
                        <a class="text-uppercase text-dark" href="">Read More <i class="bi bi-arrow-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <h4 class="text-uppercase mb-3">Custom Cake</h4>
                        <p>Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo amet tempor amet kasd lorem dolor ipsum</p>
                        <a class="text-uppercase text-dark" href="">Read More <i class="bi bi-arrow-right"></i></a>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Service Start -->





    {% endblock cake %}

project/cakeapp/templates/pages/menu.html
{% extends 'base.html' %}

{% block cake %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">Menu & Pricing</h1>
                <a href="{% url 'cake:index' %}">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="{% url 'cake:menu' %}">Menu & Pricing</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Products Start -->
    <div class="container-fluid about py-5">
        <div class="container">
            <div class="section-title position-relative text-center mx-auto mb-5 pb-3" style="max-width: 600px;">
                <h2 class="text-primary font-secondary">Menu & Pricing</h2>
                <h1 class="display-4 text-uppercase">Explore Our Cakes</h1>
            </div>

                <div class="tab-content">  
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        <div class="row g-3">
                            {% for i in contex %}
                            <div class="col-lg-6">
                                <div class="d-flex h-100">
                                    <div class="flex-shrink-0">
                                        <img class="img-fluid" src="{{i.cake_img.url}}" alt="" style="width: 150px; height: 85px;">
                                        <h4 class="bg-dark text-primary p-2 m-0">${{i.price}}</h4>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center text-start bg-secondary border-inner px-4">
                                        <h5 class="text-uppercase">{{i.title}}</h5>
                                        <span>{{i.descri}}</span>
                                        <a href="{% url 'cake:single' slug=i.slug %}" class="btn btn-success w-100">Shop Now</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Products End -->



    {% endblock cake %}

project/cakeapp/templates/pages/servise.html
{% extends 'base.html' %}

{% block cake %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">Master Chefs</h1>
                <a href="{% url 'cake:index' %}">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="{% url 'cake:chef' %}">Master Chefs</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Team Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="section-title position-relative text-center mx-auto mb-5 pb-3" style="max-width: 600px;">
                <h2 class="text-primary font-secondary">Team Members</h2>
                <h1 class="display-4 text-uppercase">Our Master Chefs</h1>
            </div>
            <div class="row g-5">
                {% for i in contex %}
                <div class="col-lg-4 col-md-6">
                    <div class="team-item">
                        <div class="position-relative overflow-hidden">
                            <img class="img-fluid w-100" src="{{i.chef_img.url}}" style="height:280px;width:150px;"  alt="img_chef">
                            <div class="team-overlay w-100 h-100 position-absolute top-50 start-50 translate-middle d-flex align-items-center justify-content-center">
                                <div class="d-flex align-items-center justify-content-start">
                                    <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 mx-1" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                                    <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 mx-1" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                                    <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 mx-1" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="bg-dark border-inner text-center p-4">
                            <h4 class="text-uppercase text-primary">{{i.name}}</h4>
                            <p class="text-white m-0">{{i.spes}}</p>
                            <br>
                            <a class="btn btn-primary col-12" href="{% url 'cake:single-chef' slug=i.slug %}" role="button">Contact</a>

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- Team End -->




{% endblock cake %}